sudo: false

os:
 - linux
 - osx

matrix:
  allow_failures:
   - os: osx
     d: gdc

language: d

d:
 - dmd-2.068.0
 - dmd-2.067.1
 - dmd-2.066.1
 - ldc-0.15.1
 - gdc

addons:
  apt:
    packages:
      - libopenmpi-dev
      - openmpi-bin
      - hwloc

install:
 - if [ $TRAVIS_OS_NAME == osx ];
   then
     brew update;
     brew install openmpi;
   fi

script:
 - dub build :configure --compiler=${DC}
 - dub build :splice --compiler=${DC}
 - gen/setup.sh
 - dub test --compiler=${DC}
 - cd examples
 - for ex in $(ls -d *); do cd $ex; dub build --build=unittest --compiler=${DC}; mpirun -c 3 $(echo $ex | tr '[:upper:]' '[:lower:]'); cd ../; done
