sudo: false

language: d

d:
 - dmd-2.068.0
 - dmd-2.067.1
 - dmd-2.066.1
 - ldc-0.15.1
 - gdc

addons:
  apt:
    packages:
      - libopenmpi-dev
      - openmpi-bin

script:
 - dub test --config=travis --compiler=${DC}
 - for ex in $(ls -d examples/*/); do dub test --config=travis --root=$ex --compiler=${DC}; done
